//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoot.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hoot.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagloba herb
        ///For each herb [clan shield, coat of arms] the blazon or verbal description of the arms is first given in authentic heraldic style, followed by a translation from the Polish description by Niesiecki. The right and left sides of a shield are identified from the standpoint of the bearer, i. e., the one holding the shield. His right would be your left and vice versa. The tinctures (colors) in heraldry are as follows: azure = blue, gules = red; sable = black; or = gold, argent = silver; vert = gree [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlResult {
            get {
                return ResourceManager.GetString("HtmlResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;&lt;strong&gt;Zagloba &lt;em&gt;herb&lt;/em&gt;&lt;/strong&gt;&lt;/h3&gt;
        ///&lt;p&gt;&lt;i&gt;&lt;img height=&quot;180&quot; alt=&quot;&quot; width=&quot;130&quot; align=&quot;left&quot; src=&quot;/Portals/0/herbarz/zaglob.gif&quot; /&gt;For each &lt;/i&gt;herb &lt;i&gt;[clan shield, coat of arms] the blazon or verbal description of the arms is first given in authentic heraldic style, followed by a translation from the Polish description by Niesiecki. The right and left sides of a shield are identified from the standpoint of the bearer, i. e., the one holding the shield. His right would be your left and vice ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlSource {
            get {
                return ResourceManager.GetString("HtmlSource", resourceCulture);
            }
        }
    }
}
